sidecar:
  dashboards:
    enabled: true
  datasources:
    enabled: true

grafana:
  additionalDataSources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus-operated:9090
    access: proxy
    isDefault: true
