apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: demo-app
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
  - name: http          # << add this
    port: 80
    targetPort: 5000
    protocol: TCP
